project:
  type: website
  output-dir: docs
  

website:
  title: "quiz2"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: life-gdp.qmd
        text: life-gdp analysis
      - href: life-population.qmd
        text: life-population analysis
      - href: country.qmd
        text: Afghanistan analysis
      - about.qmd

format:
  html:
    theme: solar
    css: style.css
    toc: true



